namespace SchoolService.Infrastructure.Tests.SchoolsDbContextFixtures;
[CollectionDefinition(nameof(SchoolsDbContextFixtureCollectionDefinition))]
public class SchoolsDbContextFixtureCollectionDefinition : ICollectionFixture<SchoolsDbContextFixture> { }